# Generated by Django 4.1.3 on 2022-11-05 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_delete_comment'),
        ('review', '0002_remove_review_name_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='music',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='musics.music'),
        ),
    ]
