# Generated by Django 4.1.3 on 2022-11-07 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musics', '0005_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='likes',
            field=models.ManyToManyField(related_name='likes_music', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_image',
            field=models.TextField(),
        ),
    ]
